function [mj_die_km,fc_kw,e_motor_peak_T,range1] = find_ev_batt_cap(powertrain_type,...
    v_req,t,timestep,drive_cycle_length,slope,Cd,Af,rho_air,veh_mass,Crr,...
    total_driven_wheelaxle_inertia,motor_in_or_out_of_wheel,number_of_driven_wheels,...
    final_drive_ratio,tire_radius,number_of_motors,front_or_rear_wheel_drive,...
    dynamic_braking,wheelbase,L1,L2,h,distance_req,distance_req_alt,fuel_tank,...
    batt_cap,overall_mass_fac,batt_V,scaling_factor,motor_selection,ESS1_selection,...
    ESS2_selection,ele_map,regen_var)

mj_die_km = 1;
scaling_factor = e_motor_peak_T/550;


for i=1:3
batt_cap = mj_die_km * range;

[max_ice_kw,total_fuel_energy,~,timestep,v_ach,~,~,~,~,~,~,~]=level_3_ev2(powertrain_type,...
    v_req,t,timestep,drive_cycle_length,slope,Cd,Af,rho_air,veh_mass,Crr,...
    total_driven_wheelaxle_inertia,motor_in_or_out_of_wheel,number_of_driven_wheels,...
    final_drive_ratio,tire_radius,number_of_motors,front_or_rear_wheel_drive,...
    dynamic_braking,wheelbase,L1,L2,h,distance_req,distance_req_alt,fuel_tank,...
    batt_cap,overall_mass_fac,batt_V,scaling_factor,motor_selection,ESS1_selection,...
    ESS2_selection,ele_map,regen_var);
    
range1 = single(trapz(t,v_ach)/1000);
mj_die_km = total_fuel_energy(i)/range1(i);
fc_kw = max_ice_kw(i);%*max_di_eff/max_ele_eff;%max_ice_kw(i);%*
e_motor_peak_T = peak_ice_T_2(i);%*max_di_eff/max_ele_eff;%peak_ice_T_2(i);%*max_di_eff/max_ele_eff;%max_ice_kw(i)*1000/peak_ice_w_2(i);
%batt_cap(i) = mj_die_km(i) * range_km(i,1);

end